### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by chetan3125** [joshfraser/robinhood-to-csv#46]
Unable to log in
Error: invalid username pass
Have not enabled 2 factro auth.
I think RH is now sending code on cell to login hence the issue.
Can you please fix ?

**Comment by miffycs** [comment]
Same issue. Following for a fix.

**Comment by KillerBeesKnees** [comment]
Same.  Any update?

**Comment by josiahredding** [comment]
same here

**Comment by kfchou** [comment]
same

**Comment by kfchou** [comment]
Found a fix based on the discussions in [this thread](https://github.com/Jamonek/Robinhood/issues/183).

Essentially, do the following:
- Go to robinhood.com. Log out if you're already logged in
- Right click > Inspect element
- Click on **Network** tab
-Enter "token" in the input line at the top where it says "Filter URLs"
- With the network monitor-er open, login to Robinhood
- You'll see two new urls pop up that say "api.robinhood.com" and "/oauth2/token"
- Click the one that's not 0 bytes in size
- Click on **Headers**, then scroll down to the **Request Payload** section
Here, you'll see new JSON parameters for your login. What you'll need here is the device token.

now, go to Robinhood.py (from this repo), edit the parameters in _fields_  (line 74) so that is looks like this:

        if mfa_code:
            fields = {
                'password' : self.password,
                'username' : self.username,
                'mfa_code': self.mfa_code,
                'grant_type': 'password',
                'client_id': self.client_id,
                'device_token': self.device_token,
                'scope': 'internal',
                'expires_in': 86400
            }
        else:
            fields = {
                'password' : self.password,
                'username' : self.username,
                'grant_type': 'password',
                'client_id': self.client_id,
                'device_token': self.device_token,
                'scope': 'internal',
                'expires_in': 86400
            }

Then, add a variable for _device_token_ after line 46
`        device_token = "[your device token]`

**Comment by anthonyk1225** [comment]
If anyone is interested, I've put some time into a similar app - [https://github.com/anthonyk1225/robinhood-to-xlsx](rh-to-xlsx)

**Comment by westonplatter** [comment]
I've appreciated and happily used robinhood-to-csv.

One option might be to get an authentication token from using https://github.com/westonplatter/fast_arrow_auth and include this in the http headers.

**Comment by anshu93** [comment]
I've submitted a PR that should solve this login issue: https://github.com/joshfraser/robinhood-to-csv/pull/50. Please review and +1 if it looks good

**Comment by johnvernam** [comment]
Looks like there may be a new issue, I am getting the following when i try to login...

Traceback (most recent call last):
  File "csv-options-export.py", line 39, in <module>
    logged_in = collect_login_data(robinhood_obj=robinhood, username=username, password=password, device_token=device_token, mfa_code=mfa_code)
  File "/Users/JohnVernam/Desktop/robinhood-to-csv-master/login_data.py", line 38, in collect_login_data
    logged_in = robinhood_obj.login(username=username, password=password, device_token=device_token)
TypeError: login() got an unexpected keyword argument 'device_token'

**Comment by planert41** [comment]
Same here! 

TypeError: login() got an unexpected keyword argument 'device_token'

**Comment by nicszerman** [comment]
Same:
```
Robinhood username: nicszerman@gmail.com
Password:
device token:
Robinhood device token:
```
Here I press enter because I don't know what to insert, and then it crashes with `TypeError: login() got an unexpected keyword argument 'device_token'`. To me this makes sense, as I have not answered what's the device_token, but I myself don't know what to insert here.

Help is greatly appreciated!

**Comment by nicszerman** [comment]
Found the following at https://github.com/anthonyk1225/robinhood-to-xlsx
```
- Log in to robinhood and open up the inspector (cmd+opt+i on mac)
- Type document.cookie in the console and copy your device_token
- Update device_token="your-device-token" [...]
```
